# Generated by Django 5.1 on 2025-04-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_pedido', models.IntegerField()),
                ('cliente', models.CharField(blank=True, max_length=255, verbose_name='Cliente')),
                ('nr_pedido_interno', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Ped.Interno')),
                ('nr_contract', models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Ped.Contract')),
                ('selecao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Selecao')),
                ('artigo', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Artigo')),
                ('produto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Produto')),
                ('quantidade', models.FloatField(blank=True, verbose_name='Qt. Pedido')),
                ('quantidade_entregue', models.CharField(blank=True, max_length=9, null=True, verbose_name='Qt. Entregue')),
                ('fechado', models.CharField(blank=True, default='Aberto', max_length=15, null=True, verbose_name='Status')),
                ('dt_pedido', models.DateTimeField(verbose_name='Data do Pedido')),
                ('dt_programada', models.DateTimeField(blank=True, null=True, verbose_name='Data do Programada')),
            ],
        ),
    ]
