# Generated by Django 5.1 on 2025-04-22 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='espessura',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='espessura'),
        ),
    ]
