# Generated by Django 4.2.16 on 2025-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pedido_espessura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='selecao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Classe'),
        ),
    ]
