# Generated by Django 4.2.16 on 2025-05-20 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_pedido_selecao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade_entregue',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Qt. Entregue'),
        ),
    ]
