# Generated by Django 4.2.16 on 2025-05-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_alter_pedido_quantidade_entregue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='fechado',
            field=models.BooleanField(default=False, verbose_name='Fechado?'),
        ),
    ]
