# Generated by Django 4.2.16 on 2025-05-26 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0037_remove_requisicao_pedido'),
        ('pedido', '0005_alter_pedido_fechado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='requisicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='fluxo.requisicao'),
        ),
    ]
