# Generated by Django 4.2.16 on 2025-05-27 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0037_remove_requisicao_pedido'),
        ('pedido', '0007_alter_pedido_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='requisicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='fluxo.requisicao'),
        ),
    ]
