# Generated by Django 4.2.16 on 2025-05-27 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0037_remove_requisicao_pedido'),
        ('pedido', '0008_alter_pedido_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='requisicao',
            field=models.ForeignKey(default=1685, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='fluxo.requisicao'),
            preserve_default=False,
        ),
    ]
