# Generated by Django 4.2.16 on 2025-05-27 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0009_alter_pedido_requisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='requisicao',
        ),
    ]
