# Generated by Django 4.2.16 on 2025-05-27 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0040_delete_pedidorequisicao'),
        ('pedido', '0010_remove_pedido_requisicao'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisicao_links', to='pedido.pedido')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_links', to='fluxo.requisicao')),
            ],
            options={
                'unique_together': {('requisicao', 'pedido')},
            },
        ),
    ]
