# Generated by Django 4.2.16 on 2025-05-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0011_pedidorequisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='classificando',
            field=models.BooleanField(default=False, verbose_name='CLASSIFICANDO?'),
        ),
    ]
