# Generated by Django 4.2.16 on 2025-05-30 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0012_pedido_classificando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='classificando',
            field=models.BooleanField(default=False, null=True, verbose_name='CLASSIFICANDO?'),
        ),
    ]
