# Generated by Django 4.2.16 on 2025-07-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0013_alter_pedido_classificando'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='obs',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Observação'),
        ),
    ]
