# Generated by Django 4.2.16 on 2025-09-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0014_pedido_obs'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='nr_pedido_interno',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='Cod.Contr'),
        ),
    ]
