# Generated by Django 4.2.16 on 2026-02-19 10:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0015_pedido_unidade_medida_alter_pedido_nr_pedido_interno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Embarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_embarque', models.DateField(default=datetime.date.today, verbose_name='Data de Embarque')),
                ('data_previsao_entrega', models.DateField(blank=True, null=True, verbose_name='Previsão de Entrega')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Embarque Finalizado?')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Observações da Carga')),
            ],
        ),
        migrations.CreateModel(
            name='TipoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de Veículo')),
                ('capacidade_m2', models.FloatField(verbose_name='Capacidade Máxima (m²)')),
                ('profundidade_util', models.FloatField(help_text='Para cálculo de acomodação', verbose_name='Profundidade Útil (m)')),
                ('largura_util', models.FloatField(default=2.4, verbose_name='Largura Útil (m)')),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome/Razão Social')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('motorista', models.CharField(blank=True, max_length=100, null=True, verbose_name='Motorista')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedido.tipoveiculo')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to='pedido.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metragem_embarcada', models.FloatField(verbose_name='Metragem Embarcada nesta Viagem')),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_embarcados', to='pedido.embarque')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_embarques', to='pedido.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='embarque',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embarques', to='pedido.veiculo'),
        ),
    ]
