# Generated by Django 4.2.16 on 2026-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0016_embarque_tipoveiculo_transportadora_veiculo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='embarque',
            name='data_previsao_entrega',
        ),
        migrations.RemoveField(
            model_name='embarque',
            name='obs',
        ),
        migrations.AddField(
            model_name='embarque',
            name='mapa_carga_json',
            field=models.JSONField(blank=True, null=True, verbose_name='Mapa de Carga (Layout)'),
        ),
    ]
