# Generated by Django 4.2.16 on 2026-02-20 16:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0017_remove_embarque_data_previsao_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemembarque',
            name='altura',
            field=models.FloatField(default=1.0, verbose_name='Altura (m)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='cd_romaneio_faturamento',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, max_length=30, verbose_name='Cd. Romaneio Faturamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='comprimento',
            field=models.FloatField(default=1.0, verbose_name='Comprimento (m)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='largura',
            field=models.FloatField(default=1.2, verbose_name='Largura (m)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='nr_pallet',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, verbose_name='Nr. Pallet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='pallet',
            field=models.CharField(default=django.utils.timezone.now, max_length=60, verbose_name='Pallet (Nr_Pallet_Nr_Embalagem)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='pecas',
            field=models.IntegerField(blank=True, null=True, verbose_name='Peças'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='pes2_original',
            field=models.FloatField(blank=True, null=True, verbose_name='Pes² (original)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='peso_liquido',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Líquido'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='pos_x',
            field=models.FloatField(default=0, verbose_name='Posição X (m)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='pos_y',
            field=models.FloatField(default=0, verbose_name='Posição Y (m)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='pos_z',
            field=models.IntegerField(default=0, verbose_name='Nível de Remonte (Z)'),
        ),
        migrations.AddField(
            model_name='itemembarque',
            name='rotacionado',
            field=models.BooleanField(default=False, verbose_name='Está Rotacionado?'),
        ),
        migrations.AlterField(
            model_name='itemembarque',
            name='metragem_embarcada',
            field=models.FloatField(verbose_name='Metragem Embarcada (m²) nesta Viagem'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.FloatField(blank=True, verbose_name='Qt. Pedido (m²)'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='unidade_medida',
            field=models.CharField(blank=True, default='M2', max_length=100, null=True, verbose_name='Unidade de Medida'),
        ),
        migrations.AddIndex(
            model_name='itemembarque',
            index=models.Index(fields=['cd_romaneio_faturamento'], name='pedido_item_cd_roma_5732c3_idx'),
        ),
        migrations.AddIndex(
            model_name='itemembarque',
            index=models.Index(fields=['nr_pallet'], name='pedido_item_nr_pall_38e20d_idx'),
        ),
        migrations.AddConstraint(
            model_name='itemembarque',
            constraint=models.UniqueConstraint(fields=('cd_romaneio_faturamento', 'nr_pallet', 'pallet'), name='uniq_romaneio_nr_pallet_pallet'),
        ),
    ]
