# Generated by Django 4.2.16 on 2026-02-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0018_itemembarque_altura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='quantidade',
            field=models.FloatField(blank=True, verbose_name='Qt. Pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='unidade_medida',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidade de Medida'),
        ),
    ]
