# Generated by Django 4.2.16 on 2026-03-31 14:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0019_alter_pedido_quantidade_alter_pedido_unidade_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrevisaoEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista', models.DateField(default=datetime.date.today, verbose_name='Data Prevista')),
                ('cliente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente (livre)')),
                ('observacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('convertido', models.BooleanField(default=False, verbose_name='Convertido em Embarque?')),
            ],
        ),
        migrations.CreateModel(
            name='PrevisaoItemEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metragem_prevista_m2', models.FloatField(verbose_name='Metragem Prevista (m²)')),
                ('cd_romaneio_faturamento', models.CharField(blank=True, max_length=30, null=True, verbose_name='Romaneio Previsto')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previsoes_embarque', to='pedido.pedido')),
                ('previsao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.previsaoembarque')),
            ],
        ),
    ]
