# Generated by Django 4.2.16 on 2026-03-31 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0020_previsaoembarque_previsaoitemembarque'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaEmbarque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metragem_prevista_m2', models.FloatField(verbose_name='Metragem Prevista (m²)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('embarque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='pedido.embarque')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_embarque', to='pedido.pedido')),
            ],
            options={
                'unique_together': {('embarque', 'pedido')},
            },
        ),
    ]
