# Generated by Django 4.2.16 on 2026-04-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0021_reservaembarque'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cidade',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='dt_embarque',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data do Embarque'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='uf',
            field=models.CharField(blank=True, default=None, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
