# Generated by Django 4.2.16 on 2026-04-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0022_pedido_cidade_pedido_dt_embarque_pedido_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='nr_pedido_cliente',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Cod. Pedido Cliente'),
        ),
    ]
