# Generated by Django 5.1 on 2025-04-25 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cd_produto', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('produto', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Produto')),
                ('quantidade', models.BigIntegerField(blank=True, null=True, verbose_name='Quantidade')),
            ],
        ),
    ]
