# Generated by Django 5.1 on 2025-04-25 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='cd_produto',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
