# Generated by Django 4.2.16 on 2025-05-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0002_alter_produto_cd_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Couro',
            fields=[
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cd_pallet', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('artigo', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Artigo')),
                ('quantidade', models.BigIntegerField(verbose_name='Quantidade')),
                ('m2', models.DecimalField(decimal_places=0.0, max_digits=10, verbose_name='M²')),
            ],
        ),
    ]
