# Generated by Django 4.2.16 on 2025-05-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0003_couro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couro',
            name='m2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='M²'),
        ),
    ]
