# Generated by Django 4.2.16 on 2026-04-02 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0004_alter_couro_m2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='produto',
            name='chegada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='consumo_diario',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='contagem_fisica',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='dolar',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='em_transito',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_anterior',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='lancado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='percentual',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='ultimo_valor',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cd_produto',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
