# Generated by Django 4.2.16 on 2026-04-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0005_remove_produto_produto_remove_produto_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='nome',
        ),
        migrations.AddField(
            model_name='produto',
            name='produto',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Produto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='cd_produto',
            field=models.BigIntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
