# Generated by Django 4.2.16 on 2026-04-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0006_remove_produto_nome_produto_produto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='consumo_diario',
        ),
        migrations.CreateModel(
            name='ConsumoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cd_requisicao', models.BigIntegerField()),
                ('peso', models.FloatField()),
                ('percentual', models.FloatField()),
                ('acrescimo', models.FloatField()),
                ('quantidade_consumida', models.FloatField()),
                ('custo_unitario', models.FloatField()),
                ('custo_total', models.FloatField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='estoque_pq.produto')),
            ],
        ),
    ]
