# Generated by Django 4.2.16 on 2026-04-13 14:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0007_remove_produto_consumo_diario_consumoproduto'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnderecoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventarioSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.DateField()),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('fechado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ContagemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=0)),
                ('uuid_mobile', models.CharField(max_length=100, unique=True)),
                ('atualizado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('origem', models.CharField(default='mobile', max_length=50)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque_pq.enderecoestoque')),
                ('inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contagens', to='estoque_pq.inventariosemanal')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoque_pq.produto')),
            ],
            options={
                'unique_together': {('inventario', 'produto', 'endereco')},
            },
        ),
    ]
