# Generated by Django 5.1 on 2025-04-07 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Nome')),
                ('meta_mes', models.IntegerField(blank=True, null=True, verbose_name='Meta mês')),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('cd_requisicao', models.IntegerField(unique=True, verbose_name='cd Requisicao')),
                ('artigo', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Artigo')),
                ('quantidade', models.BigIntegerField(blank=True, verbose_name='Quantidade')),
                ('lote', models.CharField(blank=True, max_length=15, null=True, verbose_name='Lote')),
                ('qt_entregue', models.BigIntegerField(blank=True, null=True, verbose_name='Qt. Entregue')),
                ('dt_requisicao', models.DateTimeField(blank=True, null=True, verbose_name='Data requisição')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('encerrado', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FluxoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encerrado', models.BooleanField(default=False)),
                ('dt_processo', models.DateTimeField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.processo')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxos', to='fluxo.requisicao')),
            ],
            options={
                'unique_together': {('requisicao', 'processo')},
            },
        ),
    ]
