# Generated by Django 5.1 on 2025-04-07 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0002_requisicao_pedido'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='pedido.pedido'),
        ),
    ]
