# Generated by Django 5.1 on 2025-04-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0003_alter_requisicao_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxorequisicao',
            name='qt_refila',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
