# Generated by Django 5.1 on 2025-04-14 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0004_fluxorequisicao_qt_refila'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='am',
            field=models.FloatField(blank=True, default=0, verbose_name='AM'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='exp_am',
            field=models.FloatField(blank=True, default=0, verbose_name='Expediçao AM'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='exp_m2',
            field=models.FloatField(blank=True, default=0, verbose_name='Expediçao M²'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='exp_qt',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Expediçao Qt'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='m2',
            field=models.FloatField(blank=True, default=0, verbose_name='M²'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='qt',
            field=models.BigIntegerField(blank=True, default=0, verbose_name='Qt'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='rend',
            field=models.FloatField(blank=True, default=0, verbose_name='Rendimento'),
        ),
    ]
