# Generated by Django 5.1 on 2025-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0006_alter_requisicao_am_alter_requisicao_exp_am_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='qt_refila',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
