# Generated by Django 5.1 on 2025-04-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0007_alter_fluxorequisicao_qt_refila'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='classe',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Classe'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='cor',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='espessura',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Espessura'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='ficha',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Ficha'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='nr_pedido',
            field=models.BigIntegerField(null=True, blank=True, default=0, verbose_name='Nrº Pedido'),
            preserve_default=False,
        ),
    ]
