# Generated by Django 5.1 on 2025-04-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0008_requisicao_classe_requisicao_cor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='nr_pedido',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Nrº Pedido'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='quantidade',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
    ]
