# Generated by Django 5.1 on 2025-04-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0009_alter_requisicao_nr_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='nr_pedido',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nrº Pedido'),
        ),
    ]
