# Generated by Django 5.1 on 2025-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0010_alter_requisicao_nr_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='fulao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fulão'),
        ),
    ]
