# Generated by Django 5.1 on 2025-04-24 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0011_requisicao_fulao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacao', models.CharField(blank=True, max_length=100, unique=True, verbose_name='Operação')),
                ('regulagem', models.CharField(blank=True, max_length=100, null=True, verbose_name='Regulagem')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='fluxo.processo')),
            ],
        ),
    ]
