# Generated by Django 5.1 on 2025-04-25 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0012_etapa'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoRequisicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Custo')),
                ('custo_real', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Custo Real')),
                ('adicional', models.FloatField(blank=True, default=0.0, null=True, verbose_name='Adicional')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custo', to='fluxo.requisicao')),
            ],
            options={
                'unique_together': {('requisicao',)},
            },
        ),
    ]
