# Generated by Django 5.1 on 2025-04-25 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0002_alter_produto_cd_produto'),
        ('fluxo', '0013_custorequisicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='custorequisicao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estoque_pq.produto'),
            preserve_default=False,
        ),
    ]
