# Generated by Django 5.1 on 2025-04-28 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0002_alter_produto_cd_produto'),
        ('fluxo', '0014_custorequisicao_produto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='custorequisicao',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque_pq.produto'),
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='requisicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='fluxo.requisicao'),
        ),
    ]
