# Generated by Django 5.1 on 2025-04-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0015_alter_custorequisicao_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='custo_requisicao',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Custo Requisição'),
        ),
    ]
