# Generated by Django 5.1 on 2025-04-28 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0016_requisicao_custo_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorequisicao',
            name='adicional',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Adicional'),
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='custo',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Real'),
        ),
    ]
