# Generated by Django 5.1 on 2025-04-28 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0017_alter_custorequisicao_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='custo_requisicao',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Custo Requisição'),
        ),
    ]
