# Generated by Django 5.1 on 2025-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0019_alter_requisicao_custo_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='custo_requisicao',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Custo Requisição'),
        ),
    ]
