# Generated by Django 5.1 on 2025-04-28 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0002_alter_produto_cd_produto'),
        ('fluxo', '0022_alter_custorequisicao_adicional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorequisicao',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque_pq.produto'),
        ),
    ]
