# Generated by Django 5.1 on 2025-04-28 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque_pq', '0002_alter_produto_cd_produto'),
        ('fluxo', '0023_alter_custorequisicao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorequisicao',
            name='adicional',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Adicional'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Custo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Custo Real'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='produto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='estoque_pq.produto'),
            preserve_default=False,
        ),
    ]
