# Generated by Django 5.1 on 2025-04-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0025_alter_requisicao_custo_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='custo_requisicao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo Requisicao'),
        ),
    ]
