# Generated by Django 5.1 on 2025-04-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0026_alter_requisicao_custo_requisicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custorequisicao',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo'),
        ),
        migrations.AlterField(
            model_name='custorequisicao',
            name='custo_real',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Real'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='custo_requisicao',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo Kg'),
        ),
    ]
