# Generated by Django 5.1 on 2025-04-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0027_alter_custorequisicao_custo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custorequisicao',
            name='custo_real',
        ),
        migrations.AddField(
            model_name='custorequisicao',
            name='custo_extra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Extra'),
        ),
    ]
