# Generated by Django 5.1 on 2025-04-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0028_remove_custorequisicao_custo_real_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='rendimento_custo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Rendimento Custo'),
        ),
    ]
