# Generated by Django 5.1 on 2025-04-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0029_requisicao_rendimento_custo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='custo_requisicao_inicial',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo Kg Inicial'),
        ),
    ]
