# Generated by Django 4.2.16 on 2025-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0030_requisicao_custo_requisicao_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='causa_correcao',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Causa/Correção'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='custo_requisicao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Kg Real'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='custo_requisicao_inicial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Kg Inicial'),
        ),
    ]
