# Generated by Django 4.2.16 on 2025-05-02 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0031_requisicao_causa_correcao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxorequisicao',
            name='qt_refila',
        ),
        migrations.CreateModel(
            name='Refilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt_refila', models.FloatField(blank=True, default=0.0, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.processo')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refilos', to='fluxo.requisicao')),
            ],
        ),
    ]
