# Generated by Django 4.2.16 on 2025-05-03 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0032_remove_fluxorequisicao_qt_refila_refilo'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='kg_blue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KG/M² - BLUE'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='seco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='KG/M² - SECO'),
        ),
    ]
