# Generated by Django 4.2.16 on 2025-05-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0033_requisicao_kg_blue_requisicao_seco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='dt_processo',
            field=models.DateField(blank=True, null=True),
        ),
    ]
