# Generated by Django 4.2.16 on 2025-05-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0034_alter_fluxorequisicao_dt_processo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='qt_entregue',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='qt_mt',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Qt. M²'),
        ),
    ]
