# Generated by Django 4.2.16 on 2025-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0035_remove_requisicao_qt_entregue_requisicao_qt_mt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='qt_mt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Qt. M²'),
        ),
    ]
