# Generated by Django 4.2.16 on 2025-05-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0036_alter_requisicao_qt_mt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='pedido',
        ),
    ]
