# Generated by Django 4.2.16 on 2025-05-27 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0010_remove_pedido_requisicao'),
        ('fluxo', '0037_remove_requisicao_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='pedido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requisicoes', to='pedido.pedido'),
        ),
    ]
