# Generated by Django 4.2.16 on 2025-05-27 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0039_remove_requisicao_pedido_pedidorequisicao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedidoRequisicao',
        ),
    ]
