# Generated by Django 4.2.16 on 2025-05-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0040_delete_pedidorequisicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='causa_correcao',
        ),
        migrations.AddField(
            model_name='requisicao',
            name='pallet',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Pallet'),
        ),
    ]
