# Generated by Django 4.2.16 on 2025-05-30 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0041_remove_requisicao_causa_correcao_requisicao_pallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='qt_mt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Qt. M² WB'),
        ),
    ]
