# Generated by Django 4.2.16 on 2025-06-16 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0042_alter_requisicao_qt_mt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxorequisicao',
            name='quantidade',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Qt.Peças'),
        ),
        migrations.AlterField(
            model_name='requisicao',
            name='quantidade',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Qt.Peças'),
        ),
    ]
