# Generated by Django 4.2.16 on 2025-06-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0043_fluxorequisicao_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etapa',
            name='operacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Operação'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='nome',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nome'),
        ),
    ]
