# Generated by Django 4.2.16 on 2026-02-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0044_alter_etapa_operacao_alter_processo_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='obs',
            field=models.CharField(blank=True, default=None, max_length=250, null=True, verbose_name='Observação'),
        ),
    ]
