# Generated by Django 4.2.16 on 2026-02-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0046_alter_refilo_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo.processo'),
        ),
    ]
