# Generated by Django 4.2.16 on 2026-02-25 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0047_alter_fluxorequisicao_processo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisicao',
            name='obs',
            field=models.TextField(blank=True, null=True, verbose_name='Observação'),
        ),
    ]
