# Generated by Django 4.2.16 on 2026-03-12 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0049_artigo_remove_etapa_processo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fluxorequisicao',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fluxorequisicao',
            name='artigo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo.artigo'),
        ),
        migrations.AlterUniqueTogether(
            name='fluxorequisicao',
            unique_together={('requisicao', 'artigo')},
        ),
        migrations.RemoveField(
            model_name='fluxorequisicao',
            name='processo',
        ),
    ]
