# Generated by Django 4.2.16 on 2026-03-12 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0050_alter_fluxorequisicao_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fluxorequisicao',
            old_name='artigo',
            new_name='artigos',
        ),
        migrations.AlterUniqueTogether(
            name='fluxorequisicao',
            unique_together={('requisicao', 'artigos')},
        ),
    ]
