# Generated by Django 4.2.16 on 2026-03-12 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0051_rename_artigo_fluxorequisicao_artigos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa',
            name='artigo',
        ),
        migrations.AddField(
            model_name='artigo',
            name='etapa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='etapa', to='fluxo.etapa'),
            preserve_default=False,
        ),
    ]
