# Generated by Django 4.2.16 on 2026-03-20 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0052_remove_etapa_artigo_artigo_etapa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fluxorequisicao',
            options={'ordering': ['-dt_processo', '-id'], 'verbose_name': 'Movimentação da Requisição', 'verbose_name_plural': 'Movimentações da Requisição'},
        ),
        migrations.AlterUniqueTogether(
            name='fluxorequisicao',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='artigo',
            name='etapa',
        ),
        migrations.AddField(
            model_name='fluxorequisicao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fluxo.processo'),
        ),
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='dt_processo',
            field=models.DateField(blank=True, null=True, verbose_name='Data Entrada no Processo'),
        ),
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='encerrado',
            field=models.BooleanField(default=False, verbose_name='Encerrado neste setor?'),
        ),
        migrations.RemoveField(
            model_name='fluxorequisicao',
            name='artigos',
        ),
        migrations.CreateModel(
            name='RoteiroArtigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Execução')),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roteiros', to='fluxo.artigo')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fluxo.processo')),
            ],
            options={
                'verbose_name': 'Roteiro do Artigo',
                'verbose_name_plural': 'Roteiros dos Artigos',
                'ordering': ['ordem'],
                'unique_together': {('artigo', 'processo')},
            },
        ),
    ]
