# Generated by Django 4.2.16 on 2026-03-20 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0053_alter_fluxorequisicao_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etapa',
        ),
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='dt_processo',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Entrada no Processo'),
        ),
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='processo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fluxo.processo'),
        ),
    ]
