# Generated by Django 4.2.16 on 2026-03-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0054_delete_etapa_alter_fluxorequisicao_dt_processo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='artigo_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requisicoes_vinculadas', to='fluxo.artigo', verbose_name='Artigo Genérico Vinculado'),
        ),
    ]
