# Generated by Django 4.2.16 on 2026-03-23 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxo', '0055_requisicao_artigo_padrao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='fluxo.processo', verbose_name='Setor de Trabalho')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
