# Generated by Django 4.2.16 on 2026-03-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0056_operador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fluxorequisicao',
            name='dt_processo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Entrada'),
        ),
    ]
