# Generated by Django 4.2.16 on 2026-03-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0057_alter_fluxorequisicao_dt_processo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxorequisicao',
            name='dt_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora de Saída'),
        ),
    ]
