# Generated by Django 4.2.16 on 2026-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0058_fluxorequisicao_dt_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisicao',
            name='am',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='exp_am',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='exp_m2',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='exp_qt',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='rend',
        ),
        migrations.AddField(
            model_name='custorequisicao',
            name='am',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='AM'),
        ),
        migrations.AddField(
            model_name='custorequisicao',
            name='exp_am',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Expediçao AM'),
        ),
        migrations.AddField(
            model_name='custorequisicao',
            name='exp_m2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Expediçao M²'),
        ),
        migrations.AddField(
            model_name='custorequisicao',
            name='exp_qt',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Expediçao Qt'),
        ),
        migrations.AddField(
            model_name='custorequisicao',
            name='rend',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rendimento'),
        ),
    ]
