# Generated by Django 4.2.16 on 2026-03-27 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0059_remove_requisicao_am_remove_requisicao_exp_am_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='setor',
            field=models.CharField(blank=True, choices=[('Cal', 'Caleiro'), ('Cur', 'Curtimento'), ('REC', 'Recurtimento')], max_length=3, null=True),
        ),
    ]
