# Generated by Django 4.2.16 on 2026-04-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0060_requisicao_setor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roteiroartigo',
            unique_together={('artigo', 'ordem')},
        ),
    ]
