# Generated by Django 4.2.16 on 2026-04-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0061_alter_roteiroartigo_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiroartigo',
            name='regulagem',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Regulagem'),
        ),
    ]
