# Generated by Django 4.2.16 on 2026-04-22 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0062_roteiroartigo_regulagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteiroartigo',
            name='ordem',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Ordem de Execução'),
        ),
    ]
