# Generated by Django 4.2.16 on 2026-07-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0063_alter_roteiroartigo_ordem'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='roteiroartigo',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='operador',
            name='processo',
        ),
        migrations.AddField(
            model_name='operador',
            name='processos',
            field=models.ManyToManyField(related_name='operadores', to='fluxo.processo', verbose_name='Processos de Trabalho'),
        ),
    ]
