# Generated by Django 4.2.16 on 2026-07-15 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0064_alter_roteiroartigo_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='am',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='AM'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='exp_am',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Expediçao AM'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='exp_m2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Expediçao M²'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='exp_qt',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Expediçao Qt'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='rend',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Rendimento'),
        ),
    ]
