# Generated by Django 4.2.16 on 2026-07-21 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0065_requisicao_am_requisicao_exp_am_requisicao_exp_m2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requisicao',
            name='aprovado_m2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Aprovado M²'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='aprovado_qt',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Aprovado Qt'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='grosso_m2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Grosso M²'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='grosso_qt',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Grosso Qt'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='reprovado_m2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Reprovado M²'),
        ),
        migrations.AddField(
            model_name='requisicao',
            name='reprovado_qt',
            field=models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Reprovado Qt'),
        ),
    ]
