# Generated by Django 4.2.16 on 2026-07-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0066_requisicao_aprovado_m2_requisicao_aprovado_qt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Justificativa')),
            ],
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='aprovado_m2',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='aprovado_qt',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='grosso_m2',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='grosso_qt',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='reprovado_m2',
        ),
        migrations.RemoveField(
            model_name='requisicao',
            name='reprovado_qt',
        ),
        migrations.CreateModel(
            name='RequisicaoJustificativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade de Peças')),
                ('m2_proporcional', models.FloatField(blank=True, default=0.0, null=True, verbose_name='M² Proporcional')),
                ('justificativa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uso_requisicao', to='fluxo.justificativa')),
                ('requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificativas_registadas', to='fluxo.requisicao')),
            ],
            options={
                'unique_together': {('requisicao', 'justificativa')},
            },
        ),
    ]
