# Generated by Django 4.2.16 on 2026-07-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0067_justificativa_remove_requisicao_aprovado_m2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoTintaRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('maquina', models.CharField(choices=[('MAQ1', 'Máquina 1'), ('MAQ2', 'Máquina 2'), ('CORTINA', 'Cortina'), ('TOP', 'Top')], max_length=10, verbose_name='Máquina')),
                ('consumo_kg', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Consumo (KG)')),
                ('pecas', models.IntegerField(verbose_name='Peças')),
                ('metros2', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='M²')),
                ('media_kg_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Média KG/m²')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custo Tinta — Registro',
                'verbose_name_plural': 'Custo Tinta — Registros',
                'ordering': ['-data', 'maquina'],
                'unique_together': {('data', 'maquina')},
            },
        ),
    ]
