# Generated by Django 4.2.16 on 2026-07-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0068_custo_tinta_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoFulaoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('artigo', models.CharField(max_length=150, verbose_name='Artigo')),
                ('custo_kg_inicial', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='R$/KG Inicial')),
                ('custo_kg_total', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='R$/KG Total')),
                ('rendimento', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Rendimento (m²/kg)')),
                ('custo_extra_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo Extra (R$/KG)')),
                ('custo_m2', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Custo M² (R$)')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custo Fulão — Registro',
                'verbose_name_plural': 'Custo Fulão — Registros',
                'ordering': ['-data', 'artigo'],
            },
        ),
    ]
