# Generated by Django 4.2.16 on 2026-07-31 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0069_custo_fulao_registro'),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('turno_dia', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Produção Turno Dia (m²)')),
                ('turno_noite', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Produção Turno Noite (m²)')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total (m²)')),
                ('obs', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fechamento Diário',
                'verbose_name_plural': 'Fechamentos Diários',
                'ordering': ['-data'],
            },
        ),
    ]
