# Generated by Django 4.2.16 on 2026-08-04 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0070_fechamento_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinariosBasicosRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('maquina', models.CharField(choices=[('ENXUGA', 'Enxuga'), ('ESTIRA', 'Estira'), ('VACUO', 'Vácuo'), ('ESTUFA', 'Estufa'), ('MOLISSA', 'Molissa')], max_length=20, verbose_name='Máquina')),
                ('producao', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Produção do Dia (m²)')),
                ('obs', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maquinário Básico — Registro',
                'verbose_name_plural': 'Maquinários Básicos — Registros',
                'ordering': ['-data', 'maquina'],
                'unique_together': {('data', 'maquina')},
            },
        ),
    ]
