# Generated by Django 4.2.16 on 2026-08-04 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0071_modulo4_maquinarios_basicos'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaquinariosAcabamentoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('maquina', models.CharField(choices=[('MULT1', 'Mult 1'), ('MULT2', 'Mult 2'), ('TUNEL5', 'Túnel 5')], max_length=20, verbose_name='Máquina')),
                ('pecas', models.PositiveIntegerField(verbose_name='Peças do Dia')),
                ('obs', models.TextField(blank=True, default='', verbose_name='Observação')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Maquinário Acabamento — Registro',
                'verbose_name_plural': 'Maquinários Acabamento — Registros',
                'ordering': ['-data', 'maquina'],
                'unique_together': {('data', 'maquina')},
            },
        ),
    ]
