# Generated by Django 4.2.16 on 2026-08-05 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fluxo', '0072_modulo5_maquinarios_acabamento'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MaquinariosAcabamentoRegistro',
        ),
        migrations.DeleteModel(
            name='MaquinariosBasicosRegistro',
        ),
        migrations.AddField(
            model_name='fluxorequisicao',
            name='operador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador'),
        ),
    ]
