# Generated by Django 4.2.16 on 2026-03-12 15:22

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fluxo', '0048_alter_requisicao_obs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artigo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('meta_mes', models.IntegerField(blank=True, null=True, verbose_name='Meta mês')),
            ],
        ),
        migrations.RemoveField(
            model_name='etapa',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='processo',
            name='meta_mes',
        ),
        migrations.AddField(
            model_name='etapa',
            name='artigo',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='artigo', to='fluxo.artigo'),
            preserve_default=False,
        ),
    ]
